-- Add Healthcare AI Resources
INSERT INTO public.resources (title, description, url, type, provider, difficulty_level, cost_type, duration_hours, rating, quality_score, is_core_foundational, tags, learning_outcomes, prerequisites) VALUES
('AI in Healthcare: Complete Guide', 'Comprehensive guide to AI applications in healthcare including medical imaging, diagnostics, and patient care', 'https://www.coursera.org/learn/ai-for-medicine', 'Course', 'Coursera', 'Beginner', 'Paid', 40, 4.7, 95, true, ARRAY['healthcare', 'medical-ai', 'diagnostics'], ARRAY['Understanding medical AI applications', 'Ethics in healthcare AI', 'Regulatory compliance'], ARRAY['Basic AI knowledge']),
('Medical Image Analysis with Deep Learning', 'Learn to analyze medical images using deep learning techniques for diagnosis and treatment planning', 'https://www.udacity.com/course/ai-for-healthcare-nanodegree--nd320', 'Course', 'Udacity', 'Intermediate', 'Paid', 80, 4.6, 92, false, ARRAY['medical-imaging', 'deep-learning', 'diagnosis'], ARRAY['Medical image processing', 'CNN for medical data', 'Clinical validation'], ARRAY['Python', 'Deep learning basics']),
('FDA Guidelines for AI in Medical Devices', 'Official FDA guidance on AI/ML-based medical device development and approval process', 'https://www.fda.gov/medical-devices/software-medical-device-samd/artificial-intelligence-and-machine-learning-aiml-enabled-medical-devices', 'Documentation', 'FDA', 'Advanced', 'Free', 8, 4.8, 98, false, ARRAY['regulation', 'medical-devices', 'compliance'], ARRAY['Regulatory requirements', 'Approval processes', 'Clinical trials'], ARRAY['Healthcare AI experience']);

-- Add Finance AI Resources  
INSERT INTO public.resources (title, description, url, type, provider, difficulty_level, cost_type, duration_hours, rating, quality_score, is_core_foundational, tags, learning_outcomes, prerequisites) VALUES
('Algorithmic Trading with Machine Learning', 'Build automated trading systems using ML algorithms for market analysis and strategy development', 'https://www.quantinsti.com/epat', 'Course', 'QuantInsti', 'Intermediate', 'Paid', 60, 4.5, 90, false, ARRAY['trading', 'finance', 'algorithms'], ARRAY['Trading strategies', 'Risk management', 'Portfolio optimization'], ARRAY['Python', 'Statistics']),
('Risk Management with AI', 'Apply AI techniques for credit risk assessment, fraud detection, and portfolio management', 'https://www.edx.org/course/fintech-foundations-payments-and-regulations', 'Course', 'MIT xPRO', 'Advanced', 'Paid', 45, 4.7, 93, false, ARRAY['risk-management', 'fraud-detection', 'credit-scoring'], ARRAY['Risk modeling', 'Fraud prevention', 'Regulatory compliance'], ARRAY['Finance background', 'ML experience']),
('Robo-Advisory Development', 'Build automated investment advisory platforms using AI for personalized portfolio management', 'https://github.com/microsoft/MLOps', 'Tutorial', 'Open Source', 'Intermediate', 'Free', 25, 4.4, 87, false, ARRAY['robo-advisor', 'portfolio-management', 'automation'], ARRAY['Investment algorithms', 'Client profiling', 'Portfolio rebalancing'], ARRAY['Python', 'Finance basics']);

-- Add Marketing AI Resources
INSERT INTO public.resources (title, description, url, type, provider, difficulty_level, cost_type, duration_hours, rating, quality_score, is_core_foundational, tags, learning_outcomes, prerequisites) VALUES
('AI-Powered Marketing Analytics', 'Use AI for customer segmentation, personalization, and marketing campaign optimization', 'https://www.google.com/analytics/academy/', 'Course', 'Google', 'Beginner', 'Free', 20, 4.6, 89, true, ARRAY['marketing', 'analytics', 'personalization'], ARRAY['Customer segmentation', 'Campaign optimization', 'Attribution modeling'], ARRAY['Basic analytics knowledge']),
('Conversational AI for Customer Service', 'Build chatbots and virtual assistants for customer support and engagement', 'https://www.dialogflow.com/docs', 'Documentation', 'Google Cloud', 'Intermediate', 'Free', 15, 4.5, 88, false, ARRAY['chatbots', 'customer-service', 'nlp'], ARRAY['Chatbot development', 'Intent recognition', 'Integration strategies'], ARRAY['NLP basics', 'API knowledge']),
('Recommendation Systems for E-commerce', 'Develop personalized recommendation engines for online retail and content platforms', 'https://www.tensorflow.org/recommenders', 'Tutorial', 'TensorFlow', 'Intermediate', 'Free', 30, 4.7, 91, false, ARRAY['recommendations', 'e-commerce', 'personalization'], ARRAY['Collaborative filtering', 'Content-based recommendations', 'Hybrid approaches'], ARRAY['Machine learning', 'Python']);

-- Add Education AI Resources
INSERT INTO public.resources (title, description, url, type, provider, difficulty_level, cost_type, duration_hours, rating, quality_score, is_core_foundational, tags, learning_outcomes, prerequisites) VALUES
('AI in Education: Adaptive Learning Systems', 'Create personalized learning experiences using AI for student assessment and curriculum adaptation', 'https://www.edx.org/course/artificial-intelligence-in-education', 'Course', 'edX', 'Beginner', 'Free', 35, 4.5, 86, true, ARRAY['education', 'adaptive-learning', 'assessment'], ARRAY['Learning analytics', 'Student modeling', 'Curriculum design'], ARRAY['Education background helpful']),
('Automated Essay Scoring with NLP', 'Build systems for automated evaluation of written assignments using natural language processing', 'https://www.kaggle.com/c/asap-aes', 'Competition', 'Kaggle', 'Intermediate', 'Free', 20, 4.3, 84, false, ARRAY['nlp', 'assessment', 'text-analysis'], ARRAY['Text evaluation', 'Scoring algorithms', 'Feedback generation'], ARRAY['NLP experience', 'Text processing']);