-- Add comprehensive resources to fill domain gaps and balance learning phases

-- Healthcare AI Resources
INSERT INTO public.resources (title, description, url, type, provider, difficulty_level, cost_type, duration_hours, rating, quality_score, is_core_foundational, tags, learning_outcomes, prerequisites) VALUES
('AI in Healthcare: Complete Guide', 'Comprehensive guide to AI applications in healthcare including medical imaging, diagnostics, and patient care', 'https://www.coursera.org/learn/ai-for-medicine', 'Course', 'Coursera', 'Beginner', 'Paid', 40, 4.7, 95, true, ARRAY['healthcare', 'medical-ai', 'diagnostics'], ARRAY['Understanding medical AI applications', 'Ethics in healthcare AI', 'Regulatory compliance'], ARRAY['Basic AI knowledge']),
('Medical Image Analysis with Deep Learning', 'Learn to analyze medical images using deep learning techniques for diagnosis and treatment planning', 'https://www.udacity.com/course/ai-for-healthcare-nanodegree--nd320', 'Course', 'Udacity', 'Intermediate', 'Paid', 80, 4.6, 92, false, ARRAY['medical-imaging', 'deep-learning', 'diagnosis'], ARRAY['Medical image processing', 'CNN for medical data', 'Clinical validation'], ARRAY['Python', 'Deep learning basics']),
('FDA Guidelines for AI in Medical Devices', 'Official FDA guidance on AI/ML-based medical device development and approval process', 'https://www.fda.gov/medical-devices/software-medical-device-samd/artificial-intelligence-and-machine-learning-aiml-enabled-medical-devices', 'Documentation', 'FDA', 'Advanced', 'Free', 8, 4.8, 98, false, ARRAY['regulation', 'medical-devices', 'compliance'], ARRAY['Regulatory requirements', 'Approval processes', 'Clinical trials'], ARRAY['Healthcare AI experience']),

-- Finance AI Resources  
INSERT INTO public.resources (title, description, url, type, provider, difficulty_level, cost_type, duration_hours, rating, quality_score, is_core_foundational, tags, learning_outcomes, prerequisites) VALUES
('Algorithmic Trading with Machine Learning', 'Build automated trading systems using ML algorithms for market analysis and strategy development', 'https://www.quantinsti.com/epat', 'Course', 'QuantInsti', 'Intermediate', 'Paid', 60, 4.5, 90, false, ARRAY['trading', 'finance', 'algorithms'], ARRAY['Trading strategies', 'Risk management', 'Portfolio optimization'], ARRAY['Python', 'Statistics']),
('Risk Management with AI', 'Apply AI techniques for credit risk assessment, fraud detection, and portfolio management', 'https://www.edx.org/course/fintech-foundations-payments-and-regulations', 'Course', 'MIT xPRO', 'Advanced', 'Paid', 45, 4.7, 93, false, ARRAY['risk-management', 'fraud-detection', 'credit-scoring'], ARRAY['Risk modeling', 'Fraud prevention', 'Regulatory compliance'], ARRAY['Finance background', 'ML experience']),
('Robo-Advisory Development', 'Build automated investment advisory platforms using AI for personalized portfolio management', 'https://github.com/microsoft/MLOps', 'Tutorial', 'Open Source', 'Intermediate', 'Free', 25, 4.4, 87, false, ARRAY['robo-advisor', 'portfolio-management', 'automation'], ARRAY['Investment algorithms', 'Client profiling', 'Portfolio rebalancing'], ARRAY['Python', 'Finance basics']),

-- Marketing AI Resources
INSERT INTO public.resources (title, description, url, type, provider, difficulty_level, cost_type, duration_hours, rating, quality_score, is_core_foundational, tags, learning_outcomes, prerequisites) VALUES
('AI-Powered Marketing Analytics', 'Use AI for customer segmentation, personalization, and marketing campaign optimization', 'https://www.google.com/analytics/academy/', 'Course', 'Google', 'Beginner', 'Free', 20, 4.6, 89, true, ARRAY['marketing', 'analytics', 'personalization'], ARRAY['Customer segmentation', 'Campaign optimization', 'Attribution modeling'], ARRAY['Basic analytics knowledge']),
('Conversational AI for Customer Service', 'Build chatbots and virtual assistants for customer support and engagement', 'https://www.dialogflow.com/docs', 'Documentation', 'Google Cloud', 'Intermediate', 'Free', 15, 4.5, 88, false, ARRAY['chatbots', 'customer-service', 'nlp'], ARRAY['Chatbot development', 'Intent recognition', 'Integration strategies'], ARRAY['NLP basics', 'API knowledge']),
('Recommendation Systems for E-commerce', 'Develop personalized recommendation engines for online retail and content platforms', 'https://www.tensorflow.org/recommenders', 'Tutorial', 'TensorFlow', 'Intermediate', 'Free', 30, 4.7, 91, false, ARRAY['recommendations', 'e-commerce', 'personalization'], ARRAY['Collaborative filtering', 'Content-based recommendations', 'Hybrid approaches'], ARRAY['Machine learning', 'Python']),

-- Education AI Resources
INSERT INTO public.resources (title, description, url, type, provider, difficulty_level, cost_type, duration_hours, rating, quality_score, is_core_foundational, tags, learning_outcomes, prerequisites) VALUES
('AI in Education: Adaptive Learning Systems', 'Create personalized learning experiences using AI for student assessment and curriculum adaptation', 'https://www.edx.org/course/artificial-intelligence-in-education', 'Course', 'edX', 'Beginner', 'Free', 35, 4.5, 86, true, ARRAY['education', 'adaptive-learning', 'assessment'], ARRAY['Learning analytics', 'Student modeling', 'Curriculum design'], ARRAY['Education background helpful']),
('Automated Essay Scoring with NLP', 'Build systems for automated evaluation of written assignments using natural language processing', 'https://www.kaggle.com/c/asap-aes', 'Competition', 'Kaggle', 'Intermediate', 'Free', 20, 4.3, 84, false, ARRAY['nlp', 'assessment', 'text-analysis'], ARRAY['Text evaluation', 'Scoring algorithms', 'Feedback generation'], ARRAY['NLP experience', 'Text processing']),

-- Research AI Resources
INSERT INTO public.resources (title, description, url, type, provider, difficulty_level, cost_type, duration_hours, rating, quality_score, is_core_foundational, tags, learning_outcomes, prerequisites) VALUES
('AI Research Methodology', 'Learn systematic approaches to AI research including experiment design and publication strategies', 'https://arxiv.org/abs/2009.06489', 'Research Paper', 'arXiv', 'Advanced', 'Free', 12, 4.8, 96, false, ARRAY['research', 'methodology', 'experimentation'], ARRAY['Research design', 'Statistical analysis', 'Publication process'], ARRAY['Advanced AI knowledge', 'Statistics']),
('Reproducible AI Research', 'Best practices for conducting reproducible AI experiments and sharing research code', 'https://www.nature.com/articles/s41586-020-2766-y', 'Research Paper', 'Nature', 'Advanced', 'Free', 8, 4.9, 97, false, ARRAY['reproducibility', 'research', 'best-practices'], ARRAY['Experimental design', 'Code sharing', 'Data management'], ARRAY['Research experience']),

-- Additional Specialization Phase Resources
INSERT INTO public.resources (title, description, url, type, provider, difficulty_level, cost_type, duration_hours, rating, quality_score, is_core_foundational, tags, learning_outcomes, prerequisites) VALUES
('Advanced Computer Vision Techniques', 'Deep dive into state-of-the-art computer vision including object detection, segmentation, and GANs', 'https://cs231n.stanford.edu/', 'Course', 'Stanford', 'Advanced', 'Free', 60, 4.9, 98, false, ARRAY['computer-vision', 'deep-learning', 'gan'], ARRAY['Advanced CV architectures', 'Object detection', 'Image generation'], ARRAY['CNN experience', 'Python']),
('Natural Language Processing Specialization', 'Comprehensive NLP covering transformers, BERT, GPT, and modern language models', 'https://www.deeplearning.ai/course/natural-language-processing-specialization/', 'Specialization', 'DeepLearning.AI', 'Intermediate', 'Paid', 80, 4.8, 95, false, ARRAY['nlp', 'transformers', 'language-models'], ARRAY['Transformer architectures', 'Language modeling', 'Text generation'], ARRAY['ML fundamentals', 'Python']),
('Reinforcement Learning Deep Dive', 'Advanced RL techniques including policy gradients, actor-critic methods, and multi-agent systems', 'https://spinningup.openai.com/en/latest/', 'Course', 'OpenAI', 'Advanced', 'Free', 50, 4.7, 93, false, ARRAY['reinforcement-learning', 'policy-gradients', 'multi-agent'], ARRAY['Advanced RL algorithms', 'Policy optimization', 'Multi-agent systems'], ARRAY['RL basics', 'Strong math background']),

-- Additional Practical Application Resources
INSERT INTO public.resources (title, description, url, type, provider, difficulty_level, cost_type, duration_hours, rating, quality_score, is_core_foundational, tags, learning_outcomes, prerequisites) VALUES
('MLOps in Production', 'Deploy and maintain ML models at scale using modern DevOps practices and cloud platforms', 'https://mlops-guide.github.io/', 'Guide', 'Open Source', 'Intermediate', 'Free', 35, 4.6, 90, false, ARRAY['mlops', 'deployment', 'production'], ARRAY['Model deployment', 'Monitoring', 'CI/CD for ML'], ARRAY['ML experience', 'Cloud basics']),
('Real-time AI Applications', 'Build streaming AI applications for real-time decision making and live data processing', 'https://kafka.apache.org/documentation/streams/', 'Documentation', 'Apache', 'Advanced', 'Free', 40, 4.5, 87, false, ARRAY['real-time', 'streaming', 'kafka'], ARRAY['Stream processing', 'Real-time inference', 'Event-driven architecture'], ARRAY['Distributed systems', 'ML deployment']),
('AI Product Management', 'Learn to manage AI product development from conception to market including user research and metrics', 'https://www.udemy.com/course/ai-product-manager/', 'Course', 'Udemy', 'Intermediate', 'Paid', 25, 4.4, 85, false, ARRAY['product-management', 'strategy', 'business'], ARRAY['AI product strategy', 'User research', 'Metrics and KPIs'], ARRAY['Business acumen', 'Basic AI knowledge']),
('End-to-End ML Project Workshop', 'Complete hands-on workshop building an ML application from data collection to deployment', 'https://github.com/full-stack-deep-learning/fsdl-text-recognizer-2021-labs', 'Workshop', 'Full Stack Deep Learning', 'Intermediate', 'Free', 30, 4.7, 92, false, ARRAY['end-to-end', 'project', 'hands-on'], ARRAY['Project planning', 'Data pipeline', 'Model deployment'], ARRAY['ML fundamentals', 'Python programming']),

-- Additional Free and Diverse Resources
INSERT INTO public.resources (title, description, url, type, provider, difficulty_level, cost_type, duration_hours, rating, quality_score, is_core_foundational, tags, learning_outcomes, prerequisites) VALUES
('AI for Social Good', 'Apply AI techniques to address social challenges including climate change, poverty, and healthcare access', 'https://aiforsocialgood.github.io/', 'Workshop', 'AI for Social Good', 'Beginner', 'Free', 15, 4.6, 88, true, ARRAY['social-impact', 'ethics', 'sustainability'], ARRAY['Impact assessment', 'Ethical AI design', 'Social applications'], ARRAY['Basic AI knowledge']),
('Explainable AI Techniques', 'Learn methods to interpret and explain AI model decisions for trust and transparency', 'https://christophm.github.io/interpretable-ml-book/', 'Book', 'Open Source', 'Intermediate', 'Free', 25, 4.8, 94, false, ARRAY['explainable-ai', 'interpretability', 'transparency'], ARRAY['Model interpretation', 'Feature importance', 'Bias detection'], ARRAY['ML experience']),
('AI Safety and Alignment', 'Understanding AI safety challenges and approaches to building aligned and beneficial AI systems', 'https://www.alignmentforum.org/', 'Forum', 'Alignment Forum', 'Advanced', 'Free', 20, 4.7, 91, false, ARRAY['ai-safety', 'alignment', 'future'], ARRAY['Safety considerations', 'Alignment problems', 'Future AI challenges'], ARRAY['Advanced AI knowledge']),
('Building AI Startups', 'Practical guide to founding and scaling AI-focused companies including funding and go-to-market strategies', 'https://a16z.com/2019/02/16/the-new-business-of-ai-and-how-its-different-from-traditional-software/', 'Article Series', 'Andreessen Horowitz', 'Intermediate', 'Free', 10, 4.5, 86, false, ARRAY['entrepreneurship', 'startup', 'business'], ARRAY['Business model design', 'Fundraising', 'Market strategy'], ARRAY['Business understanding', 'AI knowledge']);