// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iknrbwfchxzlepcuwvha.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlrbnJid2ZjaHh6bGVwY3V3dmhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMDk1NjcsImV4cCI6MjA3MzY4NTU2N30.E1sNTDrC3j4TJOfLgTYH9M6M0WFO2P4mYJcwLv6R6-Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});